export const projects = [
  // {
  //   id: 1,
  //   name: "St Theresa, Nyahururu School",
  //   images: ["St_Theresa_Nyahururu_School_ojwyr0"],
  //   scope: [
  //     "Full civil setup including foundations, walling and ground works",
  //     "Mechanical installation fire fighting, water storage and plumbing",
  //     "Electrical system installation and safety controls",
  //   ],
  //   outcome: [" Completed with compliance certification and handover."],
  // },
  {
    id: 2,
    name: "Trio Fuels, Thika Road Nairobi",
    images: [
      "Trio_Fuels_1_olhhni",
      "Trio_Fuels_2_d4pvhk",
      "Trio_Fuels_3_e1ejfd",
      "Trio_Fuels_4_usg3lg",
    ],
    scope: [
      "Dual fuel station built to handle both petroleum and LPG products.",
      "Full station engineering design stack and Project Management.",
      "Full civil foundation site civil and structural set up.",
      "Mechanical and installation of LPG and petroleum storage tank, piping and filing equipment.",
      "Electrical system, safety controls and comprehensive safety measures.",
    ],
    outcome: ["Completed, handed over and ready for full operations"],
  },
  {
    id: 3,
    name: "Astrol Petroleum  Redhill, Nairobi",
    images: ["Astrol_Petroleum_c5eopy"],
    scope: [
      "Full station engineering design stack.",
      "Civil works: construction of tank farm and pump house.",
      "Mechanical works: installation of LPG tank, piping, and accessories.",
      "Electrical setup and commissioning tests.",
    ],
    outcome: ["Fully functional Autogas facility with safety systems."],
  },
  {
    id: 4,
    name: "Petrocity, Thika",
    images: [
      "Petrocity_Thika_1_t4fesn",
      "Petrocity_Thika_2_ey7ygp",
      "Petrocity_Thika_3_zfn7mc",
      "Petrocity_Thika_4_dee9lh",
      "Petrocity_Thika_5_vjcekz",
    ],
    scope: [
      "Modern LPG station designed to provide safe efficient and accessible fuelling services.",
      "Civil works, foundations, paved access, buildings, and site preparation to ensure safe and compliant LPG station operations.",
      "Mechanical installation of LPG tanks, pumps and bobtail delivery points.",
      "Implementation of electrical safety systems such as emergency alarms, fire suppression and proper grounding.",
    ],
    outcome: [
      "Completed and operational with full compliance with industry safety.",
    ],
  },
  {
    id: 5,
    name: "Petrocity, Mavoko",
    images: [
      "mavoko_1_aziozi",
      "mavoko_4_fsfjlh",
      "mavoko_2_sid3ng",
      "mavoko_3_cbbn0p",
      
    ],
    scope: [
      "Strategically designed and civil construction of the fuel station.",
      "Mechanical installation of storage tanks fuelling pumps piping and all filing equipment.",
      "Electrical system and safety controls for fire suppression and proper grounding.",
    ],
    outcome: [
      "Commissioned to begin smooth operations with industry safety and guidelines.",
    ],
  },
  {
    id: 6,
    name: "OTOGAS, Buru Buru",
    images: [
      "Oto_Gas_Buru_Buru_1_edhzvs",
      "Oto_Gas_Buru_Buru_2_edmdvx",
      "Oto_Gas_Buru_Buru_3_epxixo",
      "Oto_Gas_Buru_Buru_4_gwzjci",
      "Oto_Gas_Buru_Buru_5_jnklqf",
    ],
    scope: [
      "Full station engineering design stack and Project Management.",
      "Civil site design lay out, planning and construction of the modern LPG station.",
      "Mechanical installation of LPG storage tanks piping relief systems and leak detection mechanism.",
    ],
    outcome: [
      "Fully commissioned to guarantee operational efficiency and adherence to regulatory standards.",
    ],
  },
  {
    id: 7,
    name: "Schools' LPG installations",
    images: [
      "Schools_LPG_installations_1_ddu252",
      "Schools_LPG_installations_2_efegsu",
      "Schools_LPG_installations_3_lfkxva",
      "Schools_LPG_installations_4_d2paix",
      "Schools_LPG_installations_5_m1iowd",
    ],
    scope: [
      "The LPG installation included the supply and safe installation of LPG storage tanks and cylinders, piping and distribution to kitchen appliances, and integration of pressure regulators, valves, and emergency shut-off systems.",
      "Electrical and instrumentation works that covered gas detectors, alarms, control panels, and power connections to safety devices.",
      "Civil works for tank foundations, containment bunds, access platforms, trenches, manholes and pathways to ensure safe operations. All works complied with statutory regulations (EPRA, DOSHS, Fire Safety), with proper hazard zoning and staff training for safe handling and emergency response.",
    ],
    outcome: [
      "Commissioned to reduces dependence on traditional fuels and enhances operational efficiency, with compliance with safety and environmental regulations.",
    ],
  },
  {
    id: 8,
    name: "Bobtail Fabrication, Installation & Certification",
    images: [
      "Bobtail_Installation_1_i6lje9",
      "Bobtail_Installation_2_fpb1gn",
      "Bobtail_Installation_3_fa3k5o",

      // "Bobtail_Installation_1_cjkexk",
      // "Bobtail_Installation_2_o0ohaq",
      // "Bobtail_Installation_3_vmnydn",
      // "Bobtail_Installation_4_ddeq91",
      // "Bobtail_Installation_5_fkkmmi",
    ],
    scope: [
      "Tank Installation & Vehicle Integration: Mounting and securing the tank on the chassis, including sub-frame fabrication, structural modifications, and load distribution considerations.",
      "Mechanical & Safety Systems: Installation of pumps, PTO systems, piping, manifolds, valves, hoses, meters, filters, grounding systems, and other equipment required for safe product transfer. ",
      "Electrical & Instrumentation: Installation of hazardous-area compliant electrical systems, emergency shutdown systems, lighting, gauges, metering, and monitoring instruments.",
      "Protective Coatings & Markings: Surface preparation, corrosion protection, painting, branding, hazard placards, reflective tape, and safety signage. ",
      "Testing & Commissioning: Pressure testing, leak testing, calibration, safety device verification, earthing checks, and operational commissioning. ",
      "Regulatory Compliance & Certification: Preparation of engineering documentation and coordination of inspections, approvals, licensing, and certifications with relevant authorities (EPRA, NTSA, fire safety, weights and measures), including final handover documentation and operating manuals.",
      
      // "Mechanical installation of LPG and petroleum cylinders on trucks, safe efficient unloading systems that is hoses, connections emergency shut-off valves and grounding to prevent leaks and static discharge with compliance to standards.",
      // "Bobtails painting in approved light colours (usually white) to reflect heat, prevent corrosion, and comply with safety regulations. The Paint also carries hazard markings, company details, and emergency information",
    ],
    outcome: ["Installed and put to service for safe fuel transportation"],
  },
  {
    id: 9,
    // name: "Tanks Fabrications",
    name: "Fabrication of LPG Storage Tanks",
    images: [
      "Tanks_Fabrications_1_p92axp",
      "Tanks_Fabrications_2_m6cotl",
      "Tanks_Fabrications_3_nemp7u",
    ],
    scope: [
      "Material selection, plate cutting and rolling. ",
      "Shell and head fabrication and welding. ",
      "Installation of nozzles, fittings, and tank supports.",
      "Non-destructive testing (NDT), pressure testing, and certification to verify structural integrity and safety.",
      "Surface preparation, painting, protective coatings, and nameplate installation prior to delivery. ",
      "Preparation of fabrication dossiers and quality documentation, including material certificates, welding procedures, welder qualifications, inspection and test reports, NDT reports, pressure test certificates, as-built drawings, and final handover documentation.",
      "Quality Control & Documentation: Quality control inspections are conducted throughout fabrication, including material traceability, dimensional inspections, weld visual inspections, verification of Welding Procedure Specifications (WPS), welder qualifications, and compliance with approved drawings and specifications. Documentation includes material certificates, WPS/PQR records, welder qualification records, NDT reports, pressure test certificates, inspection and test reports, as-built drawings, data books, and final handover documentation."
      // "Contracted Fabrication of LPG storage tanks in accordance with applicable engineering codes and statutory requirements. The fabrication scope includes material selection, plate cutting and rolling, shell and head welding, installation of nozzles and fittings, and provision of tank supports",
      // "All tanks undergo required non-destructive testing (NDT), pressure testing, and certification to confirm structural integrity and safety",
      // "Surface preparation, painting, and nameplate installation are completed prior to delivery to site",
    ],
    outcome: [
      "Tanks are manufactured with high quality materials, undergo required inspections and testing, and are delivered ready for safe installation and long term LPG storage, ensuring reliability, compliance, and operational safety",
    ],
  },
  {
    id: 10,
    name: "Maintenance of Autogas Stations",
    images: [
      "Maintenance_of_LPG_Stations_1_hlkdyw",
      "Maintenance_of_LPG_Stations_2_cqcl0m",
      "Maintenance_of_LPG_Stations_3_ke5wru",
      "Maintenance_of_LPG_Stations_4_aqsdle",
      "Maintenance_of_LPG_Stations_5_plwiwn",
      // "Maintenance_of_LPG_Stations_1_zniemk",
      // "Maintenance_of_LPG_Stations_2_gpswr3",
      // "Maintenance_of_LPG_Stations_3_zuo2ar",
    ],
    scope: [
      "Mechanical Inspection and servicing of LPG tanks, pumps, compressors, piping, Valve, hose, and pressure relief device inspection and replacement. Leak testing, flange tightening, and gasket replacement. Maintenance of cylinder filling equipment and emergency shutdown systems",
      "Electrical & Instrumentation inspection and maintenance of electrical panels and motors. Testing of earthing and bonding systems maintenance of Ex-proof equipment and lighting and testing and calibration of gas detection, fire alarm, and control systems",
      "Repaired concrete slabs, plinths, and equipment foundations,maintenance of drainage, bund walls, and paved areas and repair of fencing, access roads, and safety-related civil structures",
    ],
    outcome: [
      "Regular maintenance extends the lifespan of assets, supports uninterrupted operations, and ensures continued adherence to safety, environmental, and regulatory standards",
    ],
  },
  {
    id: 11,
    name: "Sugarcane Bagasse Briquettes Factory, Naitiri Bungoma",
    images: [
      "Sugarcane_Bagasse_Briquettes_Factory_Naitiri_Bungoma_1_ydmvhw",
      "Sugarcane_Bagasse_Briquettes_Factory_Naitiri_Bungoma_2_ktleqh",
      "Sugarcane_Bagasse_Briquettes_Factory_Naitiri_Bungoma_3_hxyn1v",
      "Sugarcane_Bagasse_Briquettes_Factory_Naitiri_Bungoma_4_ucz2y4",
      "Sugarcane_Bagasse_Briquettes_Factory_Naitiri_Bungoma_5_uivfbq",
      "Sugarcane_Bagasse_Briquettes_Factory_Naitiri_Bungoma_6_ekwhk8",
    ],
    scope: [
      "Civil Works: included site preparation and development activities necessary for the factory's operation. This covered clearing and excavation works, foundation construction, concrete works for production floors, drainage systems, access roads, and water management infrastructure.",
      "Structural Works: involved the design, fabrication, and erection of structural components for the factory buildings. This entailed steel and reinforced concrete structures for production halls, storage areas, machine platforms, and roofing systems.",
      "Electrical Works: covered the complete power and lighting systems for the briquette factory. This covered electrical cabling, switchboards, control panels, machine power connections, lighting installations, earthing and lightning protection systems.",
    ],
    outcome: [
      "The briquette company produces affordable, eco-friendly fuel from biomass waste, promoting sustainable energy use, waste reduction, and local economic growth.",
    ],
  },
  {
    id: 12,
    name: "Gasfil Limited,  South B Nairobi",
    images: ["Gasfil_Limited_South_B_Nairobi_uaka5e"],
    scope: [
      "Full civil setup including foundations and associated structures.",
      "Mechanical installation of 1 x 4.5MT LPG tank, piping, and filling equipment.",
      "Electrical system installation and safety controls.",
    ],
    outcome: ["Completed with compliance certification and handover."],
  },
  {
    id: 13,
    name: "Gasfil Limited , Ngong Road Nairobi",
    images: ["Gasfil_Limited_Ngong_Road_Nairobi_dc8iyf"],
    scope: [
      "Full civil setup included foundations, pavement work and associated structures.",
      "Mechanical installation of 1 x 4.5MT LPG tank, piping, and filling equipment.",
      "Electrical system installation and safety controls.",
    ],
    outcome: ["Completed with compliance certification and handover."],
  },
  {
    id: 14,
    name: " Petrocity Enterprises, Jomvu Autogas Station",
    images: ["Petrocity_Enterprises_Mazeras_Kilifi_County_d0b2mr"],
    scope: [
      "Mechanical Installation: Supply and installation of 1 x 4.5 MT LPG storage tank, LPG transfer pumps, product piping, valves, flexible connections, pressure relief valves, pressure gauges and associated process equipment. ",
      "Dispensing System: Installation of LPG dispensers, filling hoses, breakaway couplings, shear valves and vehicle filling connections for safe and accurate dispensing operations. ",
      "Electrical & Instrumentation: Installation of power distribution systems, hazardous-area compliant electrical equipment, earthing and bonding systems, emergency shutdown systems (ESD), level gauges, and associated instrumentation.",
      "Safety Systems & Compliance: Installation of firefighting equipment, gas detection systems, safety signage, hazard markings, and implementation of statutory safety requirements in accordance with applicable LPG regulations.",
      "Testing, Commissioning & Documentation: Pressure testing, leak testing, functional testing of mechanical and electrical systems, operator training, preparation of as-built documentation, and commissioning for operational readiness. ",
      "",
      // "Civil engineering: tank structure, pump house & pavement work",
      // "Mechanical installation of 1 x 4.5MT LPG tank, fuel piping, regulators & valves",
      // "Electrical works including earthing and instrumentation",
    ],
    outcome: ["Commissioned and handed over a fully operational LPG Autogas facility complete with statutory approvals, testing certificates, and comprehensive project documentation."],
  },
  {
    id: 15,
    name: "Petrocity Enterprises, Mavoko Autogas Station",
    images: ["Petrocity_Enterprises_Kyumvi_Athi_River_Machakos_County_ekfkha"],
    scope: [
      "Mechanical Installation: Supply and installation of 1 x 4.5 MT LPG storage tank, LPG transfer pumps, product piping, valves, flexible connections, pressure relief valves, pressure gauges and associated process equipment. ",
      "Dispensing System: Installation of LPG dispensers, filling hoses, breakaway couplings, shear valves and vehicle filling connections for safe and accurate dispensing operations. ",
      "Electrical & Instrumentation: Installation of power distribution systems, hazardous-area compliant electrical equipment, earthing and bonding systems, emergency shutdown systems (ESD), level gauges, and associated instrumentation.",
      "Safety Systems & Compliance: Installation of firefighting equipment, gas detection systems, safety signage, hazard markings, and implementation of statutory safety requirements in accordance with applicable LPG regulations.",
      "Testing, Commissioning & Documentation: Pressure testing, leak testing, functional testing of mechanical and electrical systems, operator training, preparation of as-built documentation, and commissioning for operational readiness. ",
      // "Civil foundation and structural setup",
      // "Mechanical works: installation of 1 x 4.5MT LPG tank, filling line & dispensers",
      // "Electrical works and system integration",
    ],
    outcome: ["Commissioned and handed over a fully operational LPG Autogas facility complete with statutory approvals, testing certificates, and comprehensive project documentation."],
  },
  {
    id: 16,
    name: "Wesco AutoGas, Eastern Bypass Ruiru",
    // name: "Accer Energy Limited,  Ngumba Lane Nairobi",
    images: ["Accer_Energy_Limited_Ngumba_Lane_Nairobi_ztfolz"],
    scope: [
      "Full civil setup included foundations and associated structures.",
      "Mechanical installation of 1 x 4.5MT LPG tank, piping, and filling equipment.",
      "Electrical system installation and safety controls.",
      // "Civil works: tank containment area, pump room foundations, canopy and pavement works",
      // "Mechanical works: installation of 2 x 2.5MT LPG tanks, dispensers, and piping",
      // "Electrical works: system wiring, grounding, instrumentation",
    ],
    outcome: ["Completed and commissioned with integrated safety systems."],
  },
];
